---
# install depends
##- name: ping hosts
##  ping:
##- name: install unzip
##  package:
##    name: "{{ item }}"
##    state: latest
##  loop:
##   - zip
##    - unzip
##    - java-11-openjdk
    
#- name: install openjdk
#  package: 
#    name: java-11-openjdk
#    state: present
##- name: java_home
##  copy:
##    src: files/java.sh
##    dest: /etc/profile.d/
##- name: download apache ignite
##  unarchive:
##    src: http://mirror.linux-ia64.org/apache//ignite/{{ apache_ignite_version }}/apache-ignite-{{ apache_ignite_version }}-bin.zip
##   dest: /usr/lib/
##    remote_src: no
- name: create ln
  file:
    path: /usr/lib/apache-ignite
    state: link
- name: create startIgnite.sh
  file:
    src: files//startIgnite.sh
    path: /usr/lib/apache-ignite/startIgnite.sh
    state: present
    mode: '0777'
- name: create production-config.xml
  file:
    src: files/production-config.xml
    path: /usr/lib/apache-ignite/config/production-config.xml
    state: present
- name: create ignite.service
  file:
    src: files/ignite.service
    path: /lib/systemd/system/ignite.service
    
    state: present
- name: daemon_reload
  systemd:
    daemon_reload: yes
- name: reload service httpd, in all cases
  systemd:
    name: ignite
    state: reloaded